teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true   # ← R1만 눌러도 안 나가게
    enable_button: 4              # L1
    enable_turbo_button: 5        # R1

    axis_linear:  {x: 1}          # 왼스틱 세로
    axis_angular: {yaw: 0}        # 왼스틱 가로

    scale_linear:        {x: 0.6}
    scale_linear_turbo:  {x: 1.2}
    scale_angular:       {yaw: 1.5}
    scale_angular_turbo: {yaw: 3.0}

